### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by niklasf**
Fixes errors such as
```
error: native library `gobject` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  gobject-sys v0.3.4
  gobject-sys v0.4.0
```
when using the [latest gtk-rs](http://gtk-rs.org/blog/2017/08/20/new-release.html).

---

Edit: I did not bump the versions of rsvg or rsvg-sys themselves, and also not: https://github.com/selaux/rsvg-rs/blob/ee77b795135fbc06a9ec9c380da1e764b95bae15/Cargo.toml#L32-L34 
So the build is expected to fail.

### CODE REVIEW

**Comment by selaux** [comment]
Thanks. I will test a little and release new versions...

**Comment by selaux** [comment]
Allright `0.2.0` has been published.

**Comment by niklasf** [comment]
Thanks :)

(Looks like I didn't understand how Gir works.)

**Comment by selaux** [comment]
Me neither 🙂

**Pull request merged**
