### PR TITLE
Update dependencies

### LINKED ISSUE #12: Gtk 0.6 compability
Please consider updating for [gtk 0.6](https://gtk-rs.org/blog/2019/02/21/new-release.html) compability.

### PR DESCRIPTION
**Pull request by jonas-schievink**
Closes #12

(disclaimer: I have no idea how all this gtk/gir stuff works)

### CODE REVIEW

**Comment by jonas-schievink** [comment]
MSRV of gtk-rs was bumped to 1.31 - how do I update that for CI? Just update the nixpkgs commit?

**Comment by jonas-schievink** [comment]
> /tmp/nix-shell-4033-0/rc: line 1:  8819 Segmentation fault      (core dumped) cargo test

Uhh

**Comment by niklasf** [comment]
I can confirm that this works nicely, despite the failures in CI.

**Comment by jonas-schievink** [comment]
Closing in favor of https://gitlab.gnome.org/GNOME/librsvg/issues/207. I'll leave the branch intact, though.

**Pull request closed without merging**
